### ISSUE TITLE
Module.save

### ISSUE THREAD

**Issue by opeltre** [opeltre/revert#9]
## Comportement actuel

Pour l'instant `ConvNet` définit une méthode `.save()` qui aggrège le `model.state_dict()` avec les paramètres de construction du réseau dans un dictionnaire ad hoc...

Apparemment `torch.load` permet de charger directement le modèle e.g. `model = torch.load("convnet-xxx.pt")` qui aurait été sauvegardé via `torch.save(model, "convnet-xxx.pt")` pourvu que la classe `ConvNet` ait été importée dans le scope local

## Todo

Ecrire les méthodes `.load` et `.save` dans models/module.py pour ne plus reposer sur ce comportement ad hoc, tester et supprimer ensuite celles de ConvNet 

- documentation torch.load: https://pytorch.org/docs/stable/generated/torch.load.html

**Comment by opeltre** [comment]
@AdrienHannon as-tu testé les méthodes save et load?

**Comment by AdrienHannon** [comment]
Oui, j'ai testé et le déplacement ne pose pas de soucis

**Comment by opeltre** [comment]
see #16 and #17
